make a new project more self-documenting

diff --git a/mulle-create-build-motd b/mulle-create-build-motd
--- a/mulle-create-build-motd
+++ b/mulle-create-build-motd
@@ -120,14 +120,20 @@ main()
 }
 
 
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env "libexec-dir" 2> /dev/null`"
    [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
-      echo "mulle-bashfunctions-env not installed" >&2 && \
-      exit 1
+            _fatal "mulle-bashfunctions-env not installed"
 
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || exit 1
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions-minimal.sh"  \
+   _fatal "failed to load mulle-bashfunctions-minimal.sh from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
 }
 
 
diff --git a/src/mulle-sde/sde/init b/src/mulle-sde/sde/init
--- a/src/mulle-sde/sde/init
+++ b/src/mulle-sde/sde/init
@@ -125,6 +125,12 @@ main()
 ###
 ### INIT
 ###
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
@@ -134,7 +140,7 @@ _init()
       then
          if [ -z "`command -v "mulle-bashfunctions-env"`" ]
          then
-            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
+            _fatal "mulle-bashfunctions-env not installed"
          else
             echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
          fi
diff --git a/src/mulle-sde/sde/init-subproject b/src/mulle-sde/sde/init-subproject
--- a/src/mulle-sde/sde/init-subproject
+++ b/src/mulle-sde/sde/init-subproject
@@ -130,14 +130,19 @@ main()
 }
 
 
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
    then
       MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env "libexec-dir" 2> /dev/null`"
       [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
-         echo "mulle-bashfunctions-env not installed" >&2 && \
-         exit 1
+         _fatal "mulle-bashfunctions-env not installed"
    fi
 
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh"  || exit 1
